title: Jon Downs, MPH
description: Epidemiologist and Data Scientist

remote_theme: pmarsceill/just-the-docs
github_repo_url: "https://doh-jpd2303.github.io/codingIX/"

# Set heading anchors
heading_anchors: true

# Activate a "Back to top" link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# A footer with "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "View this content on GitHub"
gh_edit_repository: "https://github.com/DOH-jpd2303/codingIX" # EDIT: ADD THE URL TO YOUR GITHUB REPO


gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs
gh_edit_view_mode: "tree"

# Include plugins for relative links and a remote theme
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme